#include "unit.h"
#include "dynasm/dynasm.h"
#include <stdio.h>

// DynASM directives.
|.arch x64
|.actionlist actions
#define Dst &state

void
test_int_f(void)
{
	header();
	dasm_State *state;
	dasm_init(Dst, 1);
	dasm_setup(Dst, actions);
	int num = (int)((char *)test_int_f - (char *)state);

	|  mov eax, num
	|  ret

	int (*f)() = (int (*)())dynasm_assemble(Dst);
	if (f == NULL) {
		printf("Error: f is NULL\n");
		return;
	}
	printf("int f(void); - generated by dynasm\n");
	printf("f() == num: %s\n", f() == num ? "true" : "false");
	dynasm_free((void *)f);

	footer();
}

int
main(void)
{
	test_int_f();
}
